#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Aug 03 19:00:33 CEST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=true
